"""add ondelete cascade to project

Revision ID: 04500e4515ab
Revises: 88b2a0f553e5
Create Date: 2026-02-11 11:53:00.553913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04500e4515ab'
down_revision: Union[str, Sequence[str], None] = '88b2a0f553e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('project_creator_id_fkey'), 'project', type_='foreignkey')
    op.create_foreign_key(None, 'project', 'user', ['creator_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.create_foreign_key(op.f('project_creator_id_fkey'), 'project', 'user', ['creator_id'], ['id'])
    # ### end Alembic commands ###
