"""replace file_path to filename for Document model

Revision ID: 0537879c892e
Revises: 0d8dffaf0284
Create Date: 2026-02-27 18:04:16.293228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0537879c892e'
down_revision: Union[str, Sequence[str], None] = '0d8dffaf0284'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'document', ['filename'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document', type_='unique')
    # ### end Alembic commands ###
