"""add field yjs-updates for Document

Revision ID: 0d8dffaf0284
Revises: 501abedf50dd
Create Date: 2026-02-24 23:49:38.776005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0d8dffaf0284'
down_revision: Union[str, Sequence[str], None] = '501abedf50dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('yjs_updates', postgresql.BYTEA(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'yjs_updates')
    # ### end Alembic commands ###
