"""add ondelete cascade to user_project_association

Revision ID: 152fd70a191f
Revises: 04500e4515ab
Create Date: 2026-02-11 12:49:03.153022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '152fd70a191f'
down_revision: Union[str, Sequence[str], None] = '04500e4515ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_project_association_project_id_fkey'), 'user_project_association', type_='foreignkey')
    op.drop_constraint(op.f('user_project_association_user_id_fkey'), 'user_project_association', type_='foreignkey')
    op.create_foreign_key(None, 'user_project_association', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_project_association', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_project_association', type_='foreignkey')
    op.drop_constraint(None, 'user_project_association', type_='foreignkey')
    op.create_foreign_key(op.f('user_project_association_user_id_fkey'), 'user_project_association', 'user', ['user_id'], ['id'])
    op.create_foreign_key(op.f('user_project_association_project_id_fkey'), 'user_project_association', 'project', ['project_id'], ['id'])
    # ### end Alembic commands ###
