"""create-notification-models-and-relationship

Revision ID: 30bd8db9a02d
Revises: 152fd70a191f
Create Date: 2026-02-17 18:37:16.171393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30bd8db9a02d'
down_revision: Union[str, Sequence[str], None] = '152fd70a191f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_notification',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('message_datetime', sa.DateTime(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('from_user_id', sa.UUID(), nullable=True),
    sa.Column('to_user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['from_user_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invite_notification',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('state', sa.Enum('SENT', 'ACCEPTED', 'DECLINED', name='invitestatus'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('invite_datetime', sa.DateTime(), nullable=False),
    sa.Column('from_user_id', sa.UUID(), nullable=False),
    sa.Column('to_user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['from_user_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invite_notification')
    op.drop_table('message_notification')
    # ### end Alembic commands ###
