"""add jti in RefreshToken model

Revision ID: 710feec1f7f2
Revises: 9a83b3630065
Create Date: 2026-02-01 20:06:14.898513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '710feec1f7f2'
down_revision: Union[str, Sequence[str], None] = '9a83b3630065'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_token', sa.Column('jti', sa.UUID(), nullable=False))
    op.create_unique_constraint(None, 'refresh_token', ['jti'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'refresh_token', type_='unique')
    op.drop_column('refresh_token', 'jti')
    # ### end Alembic commands ###
