"""edit user

Revision ID: 9690bf8e8e73
Revises: 43e070382d16
Create Date: 2026-02-01 17:22:31.083828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9690bf8e8e73'
down_revision: Union[str, Sequence[str], None] = '43e070382d16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'surname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'login',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'user', ['login'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'login',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'surname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
