"""add on delete cascade

Revision ID: 9a83b3630065
Revises: 9690bf8e8e73
Create Date: 2026-02-01 19:10:26.864208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a83b3630065'
down_revision: Union[str, Sequence[str], None] = '9690bf8e8e73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('refresh_token_user_id_fkey'), 'refresh_token', type_='foreignkey')
    op.create_foreign_key(None, 'refresh_token', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'refresh_token', type_='foreignkey')
    op.create_foreign_key(op.f('refresh_token_user_id_fkey'), 'refresh_token', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
